### ISSUE TITLE
Add section about MOSS

### ISSUE THREAD

**Issue by AlexIsAUsername** [wrightedu/TA-Handbook#4]
There should be a section for all the steps on how to sign up for MOSS and how to use (both on and off discord) MOSS.

**Comment by ReeseHatfield** [comment]
So the moss stuff is currently in the [118X](https://github.com/wrightedu/CS118X/tree/main/Moss) repo. TA-Handbook is currently set to public. I think other courses could benefit from MOSS.  Thoughts on moving that stuff over here instead? Maybe this repo should be private anyway? Thoughts? @AlexIsAUsername  @mkijowski

**Comment by pattonsgirl** [comment]
It should either live here or in it's own MOSS repo for WSU, but it's outgrown being siloed into just 118X.  Once we decide, we should add instructions for Discord + MOSS.

**Comment by ReeseHatfield** [comment]
Agreed. I think it could justify its own repo. Do you think we should keep it private? I don't think giving students a guide on how to make sure they won't get caught for cheating is a great idea. But I also think the students capable of doing so and checking are probably just as capable of doing the projects. But maybe that is too narrow sighted on earlier classes

**Comment by pattonsgirl** [comment]
Permission granted to migrate the MOSS information folder & related scripts to the TA handbook.  Please remove it from CS 118X post migration so that we maintain one living copy.

**Comment by ReeseHatfield** [comment]
Sounds good. I'll try to get that migrated soon. It'd be nice to have a mildly-complete guide to point new TAs towards for the Fall semester

**Comment by ReeseHatfield** [comment]
Closed by #5
